name: Run Unit Test

on:
  push:
    branches:
      - master
      - feature/unit_test
      - fix/cc_action
    paths-ignore:
      - 'README.md'
      - 'README_zh.md'
      - 'Makefile'
      - 'ruff.toml'
      - 'docker'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install "pip<24.1"
        pip install -r requirements/full.txt
        pip install "sqlite-vec==0.1.1"
        pip install pytest pytest-cov coverage codecov
    - name: Test with pytest
      run: pytest --cov
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Export coverage data as LCOV
      run: coverage lcov -o coverage.lcov
    - name: Upload coverage data to Qlty Cloud
      uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: "coverage.lcov"
